### ISSUE TITLE
implementation 'com.okta.android:okta-idx-kotlin:2.1.0' is not resolving dependencies

### ISSUE THREAD

**Issue by GaniduAsh** [okta/okta-idx-android#175]
### Describe the bug?

I was try to add version implementation 'com.okta.android:okta-idx-kotlin:2.1.0' in to my android project but unfortunately gradle throws an error Failed to resolve: com.okta.android:okta-idx-kotlin:2.1.0, 

But the module will be resolved for version 'com.okta.android:okta-idx-kotlin:2.0.0-BETA6'. 

As to https://github.com/okta/okta-idx-android/releases 2.1.0 has been released already. 

What could be the issue here ??

### What is expected to happen?

plugin 'com.okta.android:okta-idx-kotlin:2.1.0' is not resolved 

### What is the actual behavior?

latest gradle plugin should resolve

### Reproduction Steps?

add 'com.okta.android:okta-idx-kotlin:2.1.0' as a gradle dependency

### SDK Version

2.1.0

**Comment by rajdeepnanua-okta** [comment]
@GaniduAsh Thanks for catching this! It should be 'com.okta.android:idx-kotlin:2.1.0' instead of 'com.okta.android:okta-idx-kotlin:2.1.0'. I will fix this in the README

**Comment by GaniduAsh** [comment]
Awesome !!! It works
